import type { VaultEntry, FamilyMember, SharedVault } from "./types"

export const personalEntries: VaultEntry[] = [
  {
    id: "p1",
    title: "Gmail Account",
    url: "https://mail.google.com",
    login: "james@gmail.com",
    password: "Xk9#mP2$vL7!nQ4w",
    category: "Email",
    vaultType: "personal",
    lastModified: "2026-02-28",
    favorite: true,
  },
  {
    id: "p2",
    title: "GitHub",
    url: "https://github.com",
    login: "james-dev",
    password: "gH7@bR4#cT9!mW2x",
    category: "Development",
    vaultType: "personal",
    lastModified: "2026-02-25",
    favorite: true,
  },
  {
    id: "p3",
    title: "AWS Console",
    url: "https://aws.amazon.com",
    login: "james@company.com",
    password: "aW3$kL8#mN5!pQ7r",
    category: "Cloud",
    vaultType: "personal",
    lastModified: "2026-02-20",
    favorite: false,
  },
  {
    id: "p4",
    title: "LinkedIn",
    url: "https://linkedin.com",
    login: "james.doe@email.com",
    password: "lN2@kP5#rT8!wX4v",
    category: "Social",
    vaultType: "personal",
    lastModified: "2026-02-15",
    favorite: false,
  },
  {
    id: "p5",
    title: "Bank of America",
    url: "https://bankofamerica.com",
    login: "james_boa",
    password: "bA9#cD2$eF5!gH8j",
    category: "Finance",
    vaultType: "personal",
    lastModified: "2026-02-10",
    favorite: true,
  },
]

export const sharedEntries: VaultEntry[] = [
  {
    id: "s1",
    title: "Netflix Family",
    url: "https://netflix.com",
    login: "family@email.com",
    password: "nF7#xR3$kM9!bQ2w",
    category: "Entertainment",
    vaultType: "shared",
    sharedVaultId: "sv1",
    lastModified: "2026-02-27",
    favorite: true,
  },
  {
    id: "s2",
    title: "Disney+",
    url: "https://disneyplus.com",
    login: "family@email.com",
    password: "dP4@hL7#nT2!xW5v",
    category: "Entertainment",
    vaultType: "shared",
    sharedVaultId: "sv1",
    lastModified: "2026-02-26",
    favorite: false,
  },
  {
    id: "s3",
    title: "Home WiFi Router",
    url: "https://192.168.1.1",
    login: "admin",
    password: "wF8#rT5$kP3!mL9x",
    category: "Network",
    vaultType: "shared",
    sharedVaultId: "sv2",
    lastModified: "2026-02-22",
    favorite: false,
  },
  {
    id: "s4",
    title: "Family iCloud",
    url: "https://icloud.com",
    login: "family@icloud.com",
    password: "iC6@pQ9#sW4!tV7r",
    category: "Cloud",
    vaultType: "shared",
    sharedVaultId: "sv2",
    lastModified: "2026-02-18",
    favorite: true,
  },
  {
    id: "s5",
    title: "Spotify Family",
    url: "https://spotify.com",
    login: "family.spotify@email.com",
    password: "sP3#kN8$rT2!wX5v",
    category: "Entertainment",
    vaultType: "shared",
    sharedVaultId: "sv1",
    lastModified: "2026-02-14",
    favorite: false,
  },
  {
    id: "s6",
    title: "Amazon Prime",
    url: "https://amazon.com",
    login: "family@email.com",
    password: "aP7@mQ4#bR9!cL2x",
    category: "Shopping",
    vaultType: "shared",
    sharedVaultId: "sv1",
    lastModified: "2026-02-12",
    favorite: true,
  },
]

export const familyMembers: FamilyMember[] = [
  {
    id: "u1",
    name: "James",
    role: "owner",
    permission: "readwrite",
    avatar: "J",
    cryptoStatus: "synced",
    publicKey: "x25519:a1b2c3d4e5f6...",
    lastActive: "Just now",
  },
  {
    id: "u2",
    name: "Sarah",
    role: "editor",
    permission: "readwrite",
    avatar: "S",
    cryptoStatus: "synced",
    publicKey: "x25519:f6e5d4c3b2a1...",
    lastActive: "2 hours ago",
  },
  {
    id: "u3",
    name: "Alex",
    role: "viewer",
    permission: "read",
    avatar: "A",
    cryptoStatus: "pending",
    publicKey: "x25519:9g8h7i6j5k4l...",
    lastActive: "1 day ago",
  },
]

export const sharedVaults: SharedVault[] = [
  {
    id: "sv1",
    name: "Entertainment",
    memberCount: 3,
    entryCount: 4,
    members: familyMembers,
    createdBy: "u1",
  },
  {
    id: "sv2",
    name: "Home & Utilities",
    memberCount: 2,
    entryCount: 2,
    members: [familyMembers[0], familyMembers[1]],
    createdBy: "u1",
  },
]
